services:
  mysql:
    image: mysql

    container_name: mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
      MYSQL_USER: root

    ports:
      - "3307:3306"

    volumes:
      - ./volumes/mysql-data:/var/lib/mysql

    networks:
      - two-tier

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  flask-app:
    build:
      context: .

    container_name: two-tier-flask-app

    ports:
      - "5000:5000"

    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: devops

    depends_on:
      - mysql

    networks:
      - two-tier

    restart: always

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

volumes:
  mysql-data:
networks:
  two-tier:
