services:
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java_app
    volumes:
      - ./src:/app/src
    command: ["java", "Main"]
    ports:
      - "8080:8080"
